name: "Check Arbitrage Collections"
on:
  schedule:
  - cron: "30 3 */1 * *"
  workflow_dispatch: {}

jobs:
  actions:
    runs-on: ubuntu-22.04
    environment: production
    permissions: write-all
    timeout-minutes: 20
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
      
      - name: Install dependencies with pip
        run: |
          pip install -r requirements-3.txt
      
      - name: Check arbitrage collections
        env:
            URL_MONGODB: ${{ secrets.URL_MONGODB }}
            ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
            ADDRESS: ${{ secrets.ADDRESS }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            MIN_VOLUME: ${{ vars.MIN_VOLUME }}
            MIN_BID: ${{ vars.MIN_BID }}
            MIN_VOLUME_MIN_BID: ${{ vars.MIN_VOLUME_MIN_BID }}
            WORKERS: ${{ vars.WORKERS }}
            MAX_COLLECTIONS_PER_WORKER: ${{ vars.MAX_COLLECTIONS_PER_WORKER }}
            DATABASE: ${{ secrets.DATABASE }}
            COLLECTION: ${{ secrets.COLLECTION }}
        run: |
          python3 check_arbitrage_collections.py
          echo "## Checking arbitrage collections" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
      
      - name: Upload to drive
        env:
            GS_CREDENTIALS: ${{ secrets.GS_CREDENTIALS }}
            URL_MONGODB: ${{ secrets.URL_MONGODB }}
            DATABASE: ${{ secrets.DATABASE }}
            COLLECTION: ${{ secrets.COLLECTION }}
        run: |
          python3 upload_to_drive.py
          echo "## Uploading to drive" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY